# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Constants shared by the beamforming package."""

from __future__ import annotations

# Physical constants.
SPEED_OF_LIGHT_APPROX_M_PER_S = 3e8
SPEED_OF_LIGHT_EXACT_M_PER_S = 299_792_458.0

# Unit conversions.
CM_PER_METER = 100.0
MM_PER_CM = 10.0
HZ_PER_MHZ = 1e6
HZ_PER_GHZ = 1e9
BYTES_PER_MIB = 1024 * 1024
MM_PER_METER = 1000.0

# CSV codebook schema.
CODEBOOK_SECTION_MARKER = "[CODEBOOK]"
CODEBOOK_BEAM_HEADER_PREFIX = "Beam_idx"
CODEBOOK_HEADER_HORIZONTAL_ELEMENTS = "HorizontalElements"
CODEBOOK_HEADER_VERTICAL_ELEMENTS = "VerticalElements"
CODEBOOK_HEADER_DUAL_POLARIZED = "DualPolarized"
CODEBOOK_HEADER_HORIZONTAL_SPACING = "HorizontalSpacing"
CODEBOOK_HEADER_VERTICAL_SPACING = "VerticalSpacing"
CODEBOOK_HEADER_FREQUENCY_HZ = "Frequency_Hz"
CODEBOOK_REQUIRED_HEADER_KEYS = (
    CODEBOOK_HEADER_HORIZONTAL_ELEMENTS,
    CODEBOOK_HEADER_VERTICAL_ELEMENTS,
    CODEBOOK_HEADER_DUAL_POLARIZED,
    CODEBOOK_HEADER_HORIZONTAL_SPACING,
    CODEBOOK_HEADER_VERTICAL_SPACING,
    CODEBOOK_HEADER_FREQUENCY_HZ,
)
CODEBOOK_BEAM_FIXED_COLUMNS = 3
CODEBOOK_COMPLEX_PAIR_SIZE = 2

# Antenna and polarization semantics.
DUAL_POLARIZATION_COUNT = 2
SINGLE_POLARIZATION_COUNT = 1

# Logging and diagnostics.
LOG_SEPARATOR_WIDTH = 80
DEFAULT_PREVIEW_ITEM_COUNT = 3
DBM_REFERENCE_WATT = 1e-3
LOG_EPSILON = 1e-30
UE_ID_TO_FACTORY_BEAM_ID_OFFSET = 1

# JSON export schema.
BEAMFORMED_RSRP_OUTPUT_FILENAME = "beamformed_rsrp.json"
OUTPUT_RU_PREFIX = "RU_"
OUTPUT_UE_PREFIX = "UE_"
OUTPUT_BEAM_PREFIX = "BEAM_"
OUTPUT_TIME_ARRAY_KEY = "time_array"
OUTPUT_RSRP_DBM_KEY = "rsrp_dbm"

# Simulation defaults.
DEFAULT_POSITION_M = 0.0
DEFAULT_PANEL_ELEMENT_COUNT = 1
DEFAULT_PANEL_SPACING_MM = 0.0
DEFAULT_REFERENCE_FREQ_MHZ = 3500.0
DEFAULT_DUAL_POLARIZED = False

# Iceberg / S3 fetcher defaults and schema.
ICEBERG_CATALOG_NAME = "beamforming_catalog"
DEFAULT_ICEBERG_DATABASE = "default"
CFR_TABLE_NAME = "cfrs"
CFR_TABLE_FULL_NAME_TEMPLATE = "{database}.{table}"
ICEBERG_CATALOG_URI_KEY = "uri"
ICEBERG_CATALOG_TYPE_KEY = "type"
S3_ENDPOINT_PROPERTY = "s3.endpoint"
S3_ACCESS_KEY_PROPERTY = "s3.access-key-id"
S3_SECRET_KEY_PROPERTY = "s3.secret-access-key"
S3_REGION_PROPERTY = "s3.region"
DUCKDB_HTTPFS_INSTALL_SQL = "INSTALL httpfs; LOAD httpfs;"
DUCKDB_S3_ACCESS_KEY_SETTING = "s3_access_key_id"
DUCKDB_S3_SECRET_KEY_SETTING = "s3_secret_access_key"
DUCKDB_S3_ENDPOINT_SETTING = "s3_endpoint"
DUCKDB_S3_USE_SSL_SETTING = "s3_use_ssl"
DUCKDB_S3_URL_STYLE_SETTING = "s3_url_style"
DUCKDB_S3_URL_STYLE_PATH = "path"
URL_HTTP_PREFIX = "http://"
URL_HTTPS_PREFIX = "https://"
MAX_FETCH_WORKERS = 4
EMPTY_CFR_PAIR_SHAPE = (0, 0, 0)
EMPTY_CFR_TENSOR_SHAPE = (0, 0, 0, 0)
CFR_COLUMN_RU_ID = "ru_id"
CFR_COLUMN_UE_ID = "ue_id"
CFR_COLUMN_TIME_IDX = "time_idx"
CFR_COLUMN_RU_ANT_EL = "ru_ant_el"
CFR_COLUMN_UE_ANT_EL = "ue_ant_el"
CFR_COLUMN_RE = "cfr_re"
CFR_COLUMN_IM = "cfr_im"
PARQUET_SCAN_FUNCTION = "parquet_scan"
QUERY_LOG_TRUNCATE_CHARS = 200

# Plotting defaults.
AF_PATTERN_THETA_SAMPLES = 181
AF_PATTERN_PHI_SAMPLES = 361
AF_PATTERN_BORESIGHT_THETA_DEG = 90.0
AF_PATTERN_HORIZONTAL_THETA_DEG = 90.0
AF_PATTERN_VERTICAL_PHI_DEG = 0.0
AF_PATTERN_DB_FLOOR = -40.0
PATTERN_ARROW_LENGTH = 1.3
PATTERN_ARROW_LENGTH_RATIO = 0.15
PATTERN_ARROW_LINEWIDTH = 3
PATTERN_AXIS_LIMIT = 1.5
PATTERN_VIEW_ELEVATION_DEG = 20
PATTERN_VIEW_AZIMUTH_DEG = 45
PATTERN_SURFACE_ALPHA = 0.9
PATTERN_SCATTER_ELEMENT_SIZE = 100
PATTERN_SCATTER_CENTER_SIZE = 200
PATTERN_SCATTER_EDGE_WIDTH = 2
PATTERN_GEOMETRY_MARGIN_FACTOR = 1.2
PATTERN_ELEMENT_LABEL_FONTSIZE = 8
PATTERN_TITLE_FONTSIZE = 12
PATTERN_BOX_ASPECT = (1, 1, 1)
PATTERN_STEERING_COLOR = "red"
PATTERN_ELEMENT_COLOR = "blue"
PATTERN_ELEMENT_MARKER = "o"
PATTERN_CENTER_MARKER = "x"
PATTERN_EDGE_COLOR = "black"
PATTERN_FONT_WEIGHT_BOLD = "bold"
