#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

#This is an exemplary script that demonstrates the usage of the data structure that is 
# generated by running extract_CIR_sample.py. The example plots the Channel Impulse Response for one tx-rx link,
# for one instance in time.
 
import numpy as np
import argparse
import pickle
import matplotlib.pyplot as plt

# This is an exemplary script that demonstrates the usage of the data structure that is 
# generated by running extract_CIR_sample.py. The example plots the Channel Impulse Response (CIR)
# for one tx-rx link, for one instance in time. 

if __name__ == "__main__":
    base = argparse.ArgumentParser()
    base.add_argument(
        "--filename",
        type=str,
        dest="filename",
        help="Specifies the data file",
        required=True,
    )

    base.add_argument(
        "--sample",
        type=int,
        dest="sample",
        help="Specifies the sample",
        required=True,
    )

    base.add_argument(
        "--RU",
        type=int,
        dest="ru",
        help="Specifies the RU ID",
        required=True,
    )

    base.add_argument(
        "--UE",
        type=int,
        dest="ue",
        help="Specifies the UE ID",
        required=True,
    )

    base.add_argument(
        "--suppress",
        action="store_true",
        dest="is_suppress",
        default=False,
    )

    args = base.parse_args()

    ifile = open(args.filename, "rb")
    data,delay = pickle.load(ifile) #data contains the complex amplitudes and delay containes the location of multipath in seconds
    ifile.close()

    fig = plt.figure(figsize=(2 * 7.2, 2 * 4.8))

    #default to the 0th antenna element (out of n_v*n_h*n_p elements) for both RU and UE
    rx_el = 0 
    tx_el = 0

    for idx, s_key in enumerate(data.keys()): #data.key() is the sample index. 

        if s_key == args.sample: #Checks if the data file corresponds to this sample.

            cir = data[s_key][args.ru][args.ue][:, rx_el, tx_el]
            dels = delay[s_key][args.ru][args.ue][:, rx_el, tx_el] #delays are in units of seconds

            plt.plot(1e9 * dels[0:256], 20 * np.log10(np.abs(cir[0:256])) + 30, marker="o",
                        linestyle="None",
                        color="C0") #Plot in dBm

            plt.grid(True)
            plt.xlabel(r"$\tau$ [ns]")
            plt.ylabel("Power [dBm]")

    plt.savefig(f"pdp-cir-{str(args.sample).zfill(6)}.png", dpi=300)
    plt.show()

